### ISSUE TITLE
More educational BDD code

### ISSUE THREAD

**Issue by darius** [johnyf/tool_lists#15]
It's not as if there's a shortage, but for bdd.md you might like to add my https://github.com/darius/mccarthy-to-bryant with implementations in Python and Lua, from an introductory article online. The Lua version is considerably faster than lua-bdd for cases where it helps to tabulate multiple BDDs together (lua-bdd doesn't do that).

(I wish I'd had this list to check out back when I was writing it.)

**Comment by johnyf** [comment]
Thanks, 57dd80ce98e9353990c102bb52367d05ae01248f adds them.

Another approach to constructing strategies for tic-tac-toe would be to represent it as a reachability game (e.g., in temporal logic), and use fixpoint algorithms implemented with BDDs. For instance, [`omega.games.gr1`](https://github.com/johnyf/omega/blob/2cd7302c9ba2485909ca712a9adad2877371876e/omega/games/gr1.py) contains an implementation of algorithms for this purpose.

Along these lines, you may find interesting: Wolfgang Thomas, ["Solution of Church’s Problem: A Tutorial"](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.141.4577) and [some slides](http://www.itu.dk/qmc2012/wolfgangthomas.pdf) by the same author, as well as [these slides](http://www-verimag.imag.fr/~jobstman/teaching/Dagstuhl2011/3_safety.pdf) by Barbara Jobstmann.

**Comment by darius** [comment]
Thanks for the pointers!
